name: calendar_app
description: "calendar app description"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  table_calendar: ^3.0.8
  shared_preferences: ^2.2.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  path: ^1.8.2
  sqflite: ^2.2.8+4



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # 아래 부분을 추가합니다
  assets:
    - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700

  # 플랫폼 지원 명시적 설정
platforms:
    macos: true


